all:
	cp 04_suid_bin.nim /tmp/suid_bin.nim
	nim c -d:release /tmp/suid_bin.nim
	cp 05_writable_dir.nim /tmp/writable_dir.nim
	nim c -d:release /tmp/writable_dir.nim
	cp 06_writable_schedule.nim /tmp/writable_schedule.nim
	nim c -d:release /tmp/writable_schedule.nim